services:

#  Postgres - we need it for Keycloak
  postgres-keycloak:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak

#  Keycloak
  keycloak:
    depends_on:
      - postgres-keycloak
    image: bitnami/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_DATABASE_HOST=postgres-keycloak
#      - KEYCLOAK_USER=user
#      - KEYCLOAK_PASSWORD=bitnami

  #  Protected-service
  protected-service:
    depends_on:
      - keycloak
    image: ivangorbunovv/protected-service-image
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.security.oauth2.resourceserver.jwt.issuer-uri" : "http://keycloak:8080/realms/keycloak-rest-proper-way"
      }'

  #  Client-service
  client-service:
    depends_on:
      - keycloak
    image: ivangorbunovv/client-service-image
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.security.oauth2.client.provider.keycloak.token-uri" : "http://keycloak:8080/realms/keycloak-rest-proper-way/protocol/openid-connect/token",
        "spring.security.oauth2.client.registration.keycloak.client-secret" : "CxFJcA9fvnj2J22CrfQls2wzZsZpjaVf",
        "remote-service.url" : "http://protected-service:8081/api"
      }'
